### ISSUE TITLE
  Current progress!

### ISSUE THREAD

**Issue by leohoare** [jwills/dbt-mysql#1]
Hi,

Great work on this project so far!

I'm just wondering where this is sitting at as a project? Super interested in getting a mysql adapter off the ground.

After installing it from what I can see, it's somewhat working with minimal changes and isn't supporting incremental models and complaining tables already exist. Is this correct?

Thanks!

**Comment by jwills** [comment]
Hey Leo! That is roughly correct. I would also love to get it into a workable state and would be happy to talk through some of the issues I see with doing that, but I got pulled into working on some stuff related to the COVID-19 reponse that has had to take precedence over my dbt work for the time being.

Are you in the dbt Slack instance? Happy to chat more, either there or here, as time allows.

**Comment by leohoare** [comment]
slacked you through the dbt slack instance 👍
